<a href="https://colab.research.google.com/github/Psalmist70/curriculum-alignment-system/blob/main/notebooks/curriculum_alignment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
!git clone https://github.com/Psalmist70/curriculum-alignment-system.github

Cloning into 'curriculum-alignment-system.github'...
fatal: could not read Username for 'https://github.com': No such device or address

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
import pandas as pd

path = "/content/drive/MyDrive/curriculum-alignment-system/curriculum_cleaned.csv"

df = pd.read_csv(path, encoding="latin1")

df.head()

,course_id,course_title,course_description,program_outcomes,level,semester
0,CPE401,Computer Architecture and Organization,This course examines the structural and functi...,Analyze CPU components; design digital systems...,400,1
1,CSC403,Principles of Compilers,This course introduces the fundamental concept...,Explain compiler stages; implement lexical sca...,400,1
2,CPE405,Introduction to Microprocessor Technology & Mi...,This course focuses on microprocessor systems ...,Design I/O interfaces; manage interrupt struct...,400,1
3,CSC407,Techniques in Software Development,This course provides an overview of software d...,Apply software design principles; practice sof...,400,1
4,CPE409,Microprocessor Design Laboratory,This course involves practical implementation ...,Apply architectural theory; execute microcontr...,400,1

In [23]:
df.shape
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   course_id           23 non-null     object
 1   course_title        23 non-null     object
 2   course_description  23 non-null     object
 3   program_outcomes    23 non-null     object
 4   level               23 non-null     int64
 5   semester            23 non-null     int64
dtypes: int64(2), object(4)
memory usage: 1.2+ KB

In [24]:
df["desc_length"] = df["course_description"].astype(str).apply(len)
df["desc_length"].describe()

count     23.000000
mean     405.000000
std      127.544288
min      245.000000
25%      322.000000
50%      373.000000
75%      439.500000
max      709.000000
Name: desc_length, dtype: float64

In [25]:
df["course_title"] = df["course_title"].astype(str)
df["course_description"] = df["course_description"].astype(str)

In [26]:
if "program_outcomes" in df.columns:
      df["program_outcomes"] = df["program_outcomes"].astype(str)

In [27]:
df["course_description"] = df["course_description"].str.lower()
df["program_outcomes"] = df["program_outcomes"].str.lower()

In [28]:
df["course_description"] = df["course_description"].str.replace("\n", " ")
df["program_outcomes"] = df["program_outcomes"].str.replace("\n", " ")